/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-11-05 12:25:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta name=\"keywords\" content=\"jQuery DropDownList, List, ListBox, Popup List, jqxDropDownList, jqxListBox, List Widget, ListBox Widget, DropDownList Widget\" /> \r\n");
      out.write("    <meta name=\"description\" content=\"The jqxListBox can display checkboxes next to its items. You can enable this feature by setting the 'checkboxes' property to true.\"/>\r\n");
      out.write("    <title id='Description'>The jqxListBox can display checkboxes next to its items. You can enable this feature by setting the 'checkboxes' property to true. </title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../jqwidgets/styles/jqx.base.css\" type=\"text/css\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../scripts/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../scripts/demos.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../jqwidgets/jqxcore.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../jqwidgets/jqxbuttons.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../jqwidgets/jqxscrollbar.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../jqwidgets/jqxlistbox.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../jqwidgets/jqxcheckbox.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id='content'>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            $(document).ready(function () {\r\n");
      out.write("                var source = [\r\n");
      out.write("                    \"Affogato\",\r\n");
      out.write("                    \"Americano\",\r\n");
      out.write("                    \"Bicerin\",\r\n");
      out.write("                    \"Breve\",\r\n");
      out.write("                    \"CafÃ© BombÃ³n\",\r\n");
      out.write("                    \"CafÃ© au lait\",\r\n");
      out.write("                    \"CaffÃ© Corretto\",\r\n");
      out.write("                    \"CafÃ© Crema\",\r\n");
      out.write("                    \"CaffÃ© Latte\",\r\n");
      out.write("                    \"CaffÃ© macchiato\",\r\n");
      out.write("                    \"CafÃ© mÃ©lange\",\r\n");
      out.write("                    \"Coffee milk\",\r\n");
      out.write("                    \"Cafe mocha\",\r\n");
      out.write("                    \"Cappuccino\",\r\n");
      out.write("                    \"Carajillo\",\r\n");
      out.write("                    \"Cortado\",\r\n");
      out.write("                    \"Cuban espresso\",\r\n");
      out.write("                    \"Espresso\",\r\n");
      out.write("                    \"Eiskaffee\",\r\n");
      out.write("                    \"The Flat White\",\r\n");
      out.write("                    \"Frappuccino\",\r\n");
      out.write("                    \"Galao\",\r\n");
      out.write("                    \"Greek frappÃ© coffee\",\r\n");
      out.write("                    \"Iced Coffeeï»¿\",\r\n");
      out.write("                    \"Indian filter coffee\",\r\n");
      out.write("                    \"Instant coffee\",\r\n");
      out.write("                    \"Irish coffee\",\r\n");
      out.write("                    \"Liqueur coffee\"\r\n");
      out.write("\t\t        ];\r\n");
      out.write("\r\n");
      out.write("                // Create a jqxListBox\r\n");
      out.write("                $(\"#listbox\").jqxListBox({width: 200, source: source, checkboxes: true, height: 250});\r\n");
      out.write("                // Check several items.\r\n");
      out.write("                $(\"#listbox\").jqxListBox('checkIndex', 0);\r\n");
      out.write("                $(\"#listbox\").jqxListBox('checkIndex', 1);\r\n");
      out.write("                $(\"#listbox\").jqxListBox('checkIndex', 2);\r\n");
      out.write("                $(\"#listbox\").jqxListBox('checkIndex', 5);\r\n");
      out.write("\r\n");
      out.write("                $(\"#listbox\").on('checkChange', function (event) {\r\n");
      out.write("                    var args = event.args;\r\n");
      out.write("                    if (args.checked) {\r\n");
      out.write("                        $(\"#Events\").text(\"Checked: \" + args.label);\r\n");
      out.write("                    }\r\n");
      out.write("                    else {\r\n");
      out.write("                        $(\"#Events\").text(\"Unchecked: \" + args.label);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    var items = $(\"#listbox\").jqxListBox('getCheckedItems');\r\n");
      out.write("                    var checkedItems = \"\";\r\n");
      out.write("                    $.each(items, function (index) {\r\n");
      out.write("                        if (index < items.length - 1) {\r\n");
      out.write("                            checkedItems += this.label + \", \";\r\n");
      out.write("                        }\r\n");
      out.write("                        else checkedItems += this.label;\r\n");
      out.write("                    });\r\n");
      out.write("                    $(\"#CheckedItems\").text(checkedItems);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("        <div id='jqxWidget'>\r\n");
      out.write("            <div id=\"listbox\"></div>\r\n");
      out.write("            <div style=\"font-size: 13px; font-family: Verdana; margin-top: 20px;\" id=\"Events\"></div>\r\n");
      out.write("            <div style=\"font-size: 13px; font-family: Verdana; margin-top: 10px;\" id=\"CheckedItems\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
